query RunInput {
  cart {
    buyerIdentity {
      customer {
        id
        metafield(namespace: "smart_offer", key: "is_vip") {
          value
        }
      }
    }
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
    }
    lines {
      id
      quantity
      cost {
        subtotalAmount {
          amount
          currencyCode
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
    }
  }
  discountNode {
    metafield(namespace: "smart_offer", key: "function_configuration") {
      value
    }
  }
}
